### ISSUE TITLE
[Bug]: formula differ from website?

### ISSUE THREAD

**Issue by emidevops** [cnumr/EcoIndex#314]
### What happened?

`round(100` - 5 * (3 * q_dom + 2 * q_req + q_size) / 6)`

![image](https://github.com/cnumr/ecoindex_python/assets/129961128/ca1211e6-91d2-4c84-8e14-53d77e5e80ac)

### Version

^3.6

### What OS do you use?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
**🙏🏻 Praise:** Thank you for your contribution @emidevops 

I think that the documentation is not up to date because all the projects of Cnumr are using this formula from what I know:

`round(100 - 5 * (3 * q_dom + 2 * q_req + q_size) / 6)`

https://github.com/cnumr/GreenIT-Analysis/blob/ca1d15baa5cc0ee02a13a2a49b332704de0cb476/script/ecoIndex.js#L34

https://github.com/cnumr/GreenIT-Analysis-cli/blob/9c1f010ad939782fab6fa1033d0ac267da547760/greenit-core/ecoIndex.js#L35

https://github.com/cnumr/ecoindex_js/blob/3b58a54abff149da7944e707132eec8242e00227/src/index.js#L35

@bordage can you confirm?

**Comment by tbroyer** [comment]
Doesn't that directly depend on how the q-values are computed? In the above links, if the `computeQuantile` functions multiplied their result by 5 then the final formula would be the same as the one on the website.
(and that 5 factor is due to the fact that computeQuantile currently returns a value between 0 and 20, not between 0 and 100)

**Comment by bordage** [comment]
@tbroyer  : you are right.  That's the good answer.
